"""Scaffold a .projio workspace inside a project directory."""
from __future__ import annotations

import re
from pathlib import Path

from .config import load_project_config

KIND_CHOICES = ("generic", "tool", "study")

BASE_PROJIO_CONFIG = """\
# projio workspace config
project_name: {name}
project_kind: {kind}
description: ""

indexio:
  config: .indexio/config.yaml        # path to indexio config
  persist_dir: .projio/index           # chroma db location

biblio:
  enabled: true
  config: bib/config/biblio.yml

notio:
  enabled: true
  notes_dir: notes/

codio:
  enabled: true
  catalog_path: .codio/catalog.yml
  profiles_path: .codio/profiles.yml
  notes_dir: docs/reference/codelib/libraries/

site:
  base_port: 8000
  host: "127.0.0.1"
  chatbot:
    enabled: false
    backend_url: null
    host: "127.0.0.1"
    port: 9100
    title: "Docs Assistant"
    storage_key: "{name}_chat_v1"

helpers:
  sibling:
    github:
      sibling: github
      credential: github
      project_template: "{{project_name}}"
    gitlab:
      sibling: gitlab
      credential: gitlab
      project_template: "{{project_name}}"
    ria:
      sibling: origin
      alias_strategy: basename
  docs:
    mkdocs:
      enabled: false
"""

STUDY_PROJIO_CONFIG = """\
# projio workspace config
project_name: {name}
project_kind: study
description: ""

indexio:
  config: .indexio/config.yaml        # path to indexio config
  persist_dir: .projio/index           # chroma db location

biblio:
  enabled: false
  config: bib/config/biblio.yml

notio:
  enabled: false
  notes_dir: notes/

site:
  base_port: 8000
  host: "127.0.0.1"
  chatbot:
    enabled: false
    backend_url: null
    host: "127.0.0.1"
    port: 9100
    title: "Docs Assistant"
    storage_key: "{name}_chat_v1"

helpers:
  sibling:
    github:
      sibling: github
      credential: github
      project_template: "{{project_name}}"
    gitlab:
      sibling: gitlab
      credential: gitlab
      project_template: "{{project_name}}"
    ria:
      sibling: origin
      alias_strategy: basename
  docs:
    mkdocs:
      enabled: false
"""

PROJIO_MK = """\
# projio.mk — shared targets, managed by projio
# Include from your Makefile: -include .projio/projio.mk

PYTHON  ?= python
DATALAD ?= datalad
PROJIO  ?= $(PYTHON) -m projio
MSG     ?= Update

.PHONY: save push
.PHONY: projio-init projio-config-user projio-config-show projio-status projio-auth
.PHONY: projio-gh projio-gl projio-ria site-build site-serve site-stop site-list site-detect mcp

# --- DataLad targets ---
save:
\t$(DATALAD) save -m "$(MSG)"

push:
\t$(DATALAD) push --to github

# --- Projio targets ---
projio-init:
\t$(PROJIO) init .

projio-config-user:
\t$(PROJIO) config init-user

projio-config-show:
\t$(PROJIO) config -C . show

projio-status:
\t$(PROJIO) status -C .

projio-auth:
\t$(PROJIO) auth -C . doctor

projio-gh:
\t$(PROJIO) sibling -C . github

projio-gl:
\t$(PROJIO) sibling -C . gitlab

projio-ria:
\t$(PROJIO) sibling -C . ria

site-build:
\t$(PROJIO) site build -C .

site-serve:
\t$(PROJIO) site serve -C .

site-stop:
\t$(PROJIO) site stop -C . --all

site-list:
\t$(PROJIO) site list -C .

site-detect:
\t$(PROJIO) site detect -C .

mcp:
\t$(PROJIO) mcp -C .
"""

_PROJIO_INCLUDE = "-include .projio/projio.mk"

DEFAULT_MAKEFILE_SNIPPET = """\
# generated by projio init
PYTHON  ?= python
DATALAD ?= datalad
MSG     ?= Update

-include .projio/projio.mk
"""

TOOL_MAKEFILE_APPEND = """

.PHONY: test build check publish-test publish clean

test:
\tPYTHONPATH=src $(PYTHON) -m pytest tests -q

build:
\t$(PYTHON) -m build

check:
\t$(PYTHON) -m twine check dist/*

publish-test:
\t$(PYTHON) -m twine upload --repository testpypi dist/*

publish:
\t$(PYTHON) -m twine upload dist/*

clean:
\trm -rf build dist .pytest_cache .mypy_cache src/*.egg-info
"""

DEFAULT_MKDOCS = """\
site_name: {name}
docs_dir: docs
theme:
  name: material
"""

TOOL_PYPROJECT = """\
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{distribution_name}"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [{{ name = "" }}]
license = {{ text = "MIT" }}
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "build", "twine"]

[tool.setuptools.packages.find]
where = ["src"]
"""

TOOL_INIT = '''"""Top-level package for {package_name}."""\n'''

TOOL_TEST = """from __future__ import annotations


def test_import() -> None:
    import {package_name}

    assert {package_name}.__name__ == "{package_name}"
"""

STUDY_DOC = """# Study Overview

This project was scaffolded with `projio init . --kind study`.

Keep this thin:

- document project purpose and scope
- use `projio` for shared repo plumbing
- add domain-specific workflow structure only when the project actually needs it
"""


def _normalize_package_name(name: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_]+", "_", name.strip().lower())
    slug = re.sub(r"_+", "_", slug).strip("_")
    if not slug:
        slug = "proj"
    if slug[0].isdigit():
        slug = f"pkg_{slug}"
    return slug


def _write_if_needed(path: Path, content: str, root: Path, *, force: bool) -> None:
    if path.exists() and not force:
        print(f"[SKIP] {path.relative_to(root)} already exists")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"[OK] wrote {path.relative_to(root)}")


def _projio_config_for_kind(name: str, kind: str) -> str:
    if kind == "study":
        return STUDY_PROJIO_CONFIG.format(name=name)
    return BASE_PROJIO_CONFIG.format(name=name, kind=kind)


def _makefile_for_kind(kind: str) -> str:
    if kind == "tool":
        return DEFAULT_MAKEFILE_SNIPPET + TOOL_MAKEFILE_APPEND
    return DEFAULT_MAKEFILE_SNIPPET


def _ensure_makefile_include(path: Path, root: Path) -> None:
    """Ensure an existing Makefile contains the projio.mk include directive."""
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8")
    if _PROJIO_INCLUDE in text:
        return
    path.write_text(text.rstrip("\n") + "\n\n" + _PROJIO_INCLUDE + "\n", encoding="utf-8")
    print(f"[OK] added projio.mk include to {path.relative_to(root)}")


def _scaffold_base(root: Path, *, kind: str, force: bool) -> None:
    proj_dir = root / ".projio"
    proj_dir.mkdir(parents=True, exist_ok=True)
    _write_if_needed(proj_dir / "config.yml", _projio_config_for_kind(root.name, kind), root, force=force)
    # projio.mk is projio-managed — always overwrite to pick up new targets
    _write_if_needed(proj_dir / "projio.mk", PROJIO_MK, root, force=True)
    _write_if_needed(root / "mkdocs.yml", DEFAULT_MKDOCS.format(name=root.name), root, force=force)
    _write_if_needed(root / "Makefile", _makefile_for_kind(kind), root, force=force)
    _ensure_makefile_include(root / "Makefile", root)
    docs_dir = root / "docs"
    docs_dir.mkdir(exist_ok=True)
    _write_if_needed(docs_dir / "index.md", f"# {root.name}\n", root, force=force)


def _scaffold_tool(root: Path, *, force: bool) -> None:
    package_name = _normalize_package_name(root.name)
    _write_if_needed(
        root / "pyproject.toml",
        TOOL_PYPROJECT.format(distribution_name=root.name, package_name=package_name),
        root,
        force=force,
    )
    _write_if_needed(root / "src" / package_name / "__init__.py", TOOL_INIT.format(package_name=package_name), root, force=force)
    tests_dir = root / "tests"
    tests_dir.mkdir(exist_ok=True)
    _write_if_needed(root / "tests" / f"test_{package_name}.py", TOOL_TEST.format(package_name=package_name), root, force=force)


def _scaffold_study(root: Path, *, force: bool) -> None:
    _write_if_needed(root / "docs" / "study-overview.md", STUDY_DOC, root, force=force)


def scaffold(root: str | Path, *, kind: str = "generic", force: bool = False) -> None:
    """Scaffold project files inside *root*."""
    if kind not in KIND_CHOICES:
        raise ValueError(f"Unknown project kind: {kind}")
    root_path = Path(root).expanduser().resolve()
    _scaffold_base(root_path, kind=kind, force=force)
    if kind == "tool":
        _scaffold_tool(root_path, force=force)
    elif kind == "study":
        _scaffold_study(root_path, force=force)


def load_projio_config(root: str | Path) -> dict:
    return load_project_config(root)
