"""MCP tools: questio research orchestration — docs generation from plan YAML."""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

from .common import JsonDict, get_project_root, json_dict


def _parse_frontmatter(path: Path) -> dict[str, Any]:
    """Parse YAML frontmatter from a markdown file."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        return yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return {}


def _collect_results(root: Path) -> list[dict[str, Any]]:
    """Scan docs/log/result/ for result notes, return parsed frontmatter list."""
    result_dir = root / "docs" / "log" / "result"
    if not result_dir.is_dir():
        return []
    results = []
    for path in sorted(result_dir.glob("result-*.md")):
        fm = _parse_frontmatter(path)
        if fm:
            fm["_path"] = path
            fm["_filename"] = path.stem
            results.append(fm)
    return results


def _question_milestone_map(
    questions: dict[str, dict],
) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """Build question→milestones and milestone→questions mappings."""
    q_to_m: dict[str, list[str]] = {}
    m_to_q: dict[str, list[str]] = defaultdict(list)
    for qid, qdata in questions.items():
        ms = qdata.get("milestones", []) or []
        q_to_m[qid] = list(ms)
        for m in ms:
            m_to_q[m].append(qid)
    return q_to_m, dict(m_to_q)


def _results_by_question(results: list[dict[str, Any]]) -> dict[str, list[dict]]:
    """Group results by question ID."""
    by_q: dict[str, list[dict]] = defaultdict(list)
    for r in results:
        qs = r.get("question", [])
        if isinstance(qs, str):
            qs = [qs]
        for q in qs:
            by_q[q].append(r)
    return dict(by_q)


def _results_by_milestone(results: list[dict[str, Any]]) -> dict[str, list[dict]]:
    """Group results by milestone."""
    by_m: dict[str, list[dict]] = defaultdict(list)
    for r in results:
        ms = r.get("milestone", "")
        if isinstance(ms, str) and ms:
            by_m[ms].append(r)
        elif isinstance(ms, list):
            for m in ms:
                by_m[m].append(r)
    return dict(by_m)


def _milestone_status_summary(
    milestones: dict[str, dict], milestone_ids: list[str],
) -> str:
    """Return 'x/y' string for completed milestones out of total."""
    done = sum(
        1 for mid in milestone_ids
        if milestones.get(mid, {}).get("status") in ("complete", "done")
    )
    return f"{done}/{len(milestone_ids)}"


def _status_class(status: str) -> str:
    """Map status string to mermaid CSS class."""
    if status in ("complete", "done", "confirmed", "sufficient"):
        return "done"
    if status in ("in_progress", "in progress"):
        return "progress"
    return "pending"


def _sanitize_label(text: str) -> str:
    """Sanitize text for mermaid node labels."""
    return text.replace('"', "'").replace("\n", " ")


# ---------------------------------------------------------------------------
# Page generators
# ---------------------------------------------------------------------------


def _generate_questions_md(
    questions: dict[str, dict],
    milestones: dict[str, dict],
    results_by_q: dict[str, list[dict]],
    q_to_m: dict[str, list[str]],
) -> str:
    """Generate questions.md — research question registry table."""
    lines = [
        "# Research Questions",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
        "| ID | Question | Type | Status | Milestones | Evidence | Section |",
        "|----|----------|------|--------|------------|----------|---------|",
    ]
    for qid, qdata in questions.items():
        text = qdata.get("text", "")
        qtype = qdata.get("type", "")
        status = qdata.get("status", "not_started")
        ms_ids = q_to_m.get(qid, [])
        ms_summary = _milestone_status_summary(milestones, ms_ids)
        evidence_count = len(results_by_q.get(qid, []))
        section = qdata.get("manuscript_section", "")
        if section:
            section_link = f"[{section}](../manuscript/{section}/)"
        else:
            section_link = "—"
        lines.append(
            f"| {qid} | {text} | {qtype} | {status} "
            f"| {ms_summary} | {evidence_count} results | {section_link} |"
        )
    lines.append("")
    return "\n".join(lines)


def _generate_milestones_md(
    questions: dict[str, dict],
    milestones: dict[str, dict],
    m_to_q: dict[str, list[str]],
    results_by_m: dict[str, list[dict]],
) -> str:
    """Generate milestones.md — milestone tracker grouped by question."""
    lines = [
        "# Milestones",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
    ]

    # Assign milestones to groups.  A milestone belongs to a question group
    # if it serves exactly one question.  Milestones serving multiple questions
    # go into "Shared Prerequisites".
    grouped: dict[str, list[str]] = defaultdict(list)  # group label → [mid]
    shared: list[str] = []
    assigned: set[str] = set()

    for mid in milestones:
        qs = m_to_q.get(mid, [])
        if len(qs) == 1:
            grouped[qs[0]].append(mid)
            assigned.add(mid)
        elif len(qs) > 1:
            shared.append(mid)
            assigned.add(mid)

    # Milestones not referenced by any question
    orphan = [mid for mid in milestones if mid not in assigned]
    if orphan:
        shared.extend(orphan)

    def _milestone_table(milestone_ids: list[str]) -> list[str]:
        tbl = [
            "| Milestone | Status | Pipeline | Depends on | Evidence |",
            "|-----------|--------|----------|------------|----------|",
        ]
        for mid in milestone_ids:
            mdata = milestones.get(mid, {})
            desc = mdata.get("description", mid)
            status = mdata.get("status", "not_started")
            pipes = ", ".join(mdata.get("pipelines", []) or [])
            deps = ", ".join(mdata.get("depends_on", []) or []) or "—"
            evidence_list = results_by_m.get(mid, [])
            if evidence_list:
                ev_links = ", ".join(
                    f"[{r['_filename']}](../log/result/{r['_filename']}/)"
                    for r in evidence_list
                )
            else:
                ev_links = ""
            tbl.append(f"| {desc} | {status} | {pipes} | {deps} | {ev_links} |")
        return tbl

    # Shared prerequisites first
    if shared:
        lines.append("## Shared Prerequisites")
        lines.append("")
        lines.extend(_milestone_table(shared))
        lines.append("")

    # Per-question groups
    for qid, qdata in questions.items():
        q_milestones = grouped.get(qid, [])
        if not q_milestones:
            continue
        text = qdata.get("text", qid)
        lines.append(f"## {qid}: {text}")
        lines.append("")
        lines.extend(_milestone_table(q_milestones))
        lines.append("")

    return "\n".join(lines)


def _generate_roadmap_md(milestones: dict[str, dict]) -> str:
    """Generate roadmap.md — mermaid dependency graph with status coloring."""
    lines = [
        "# Roadmap",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
        "```mermaid",
        "graph LR",
    ]

    # Emit nodes
    for mid, mdata in milestones.items():
        desc = _sanitize_label(mdata.get("description", mid))
        status = mdata.get("status", "not_started")
        cls = _status_class(status)
        node_id = f"M_{mid.replace('-', '_')}"
        lines.append(f'    {node_id}["{desc}"]:::{cls}')

    lines.append("")

    # Emit edges
    for mid, mdata in milestones.items():
        deps = mdata.get("depends_on", []) or []
        target = f"M_{mid.replace('-', '_')}"
        for dep in deps:
            source = f"M_{dep.replace('-', '_')}"
            lines.append(f"    {source} --> {target}")

    lines.append("")
    lines.append("    classDef done fill:#2d6a4f,stroke:#1b4332,color:#fff")
    lines.append("    classDef progress fill:#e9c46a,stroke:#f4a261,color:#000")
    lines.append("    classDef pending fill:#adb5bd,stroke:#6c757d,color:#000")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def _generate_evidence_md(
    questions: dict[str, dict],
    milestones: dict[str, dict],
    results_by_q: dict[str, list[dict]],
    q_to_m: dict[str, list[str]],
) -> str:
    """Generate evidence.md — per-question evidence dossier."""
    lines = [
        "# Evidence",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
    ]
    for qid, qdata in questions.items():
        text = qdata.get("text", qid)
        status = qdata.get("status", "not_started")
        ms_ids = q_to_m.get(qid, [])
        ms_summary = _milestone_status_summary(milestones, ms_ids)
        q_results = results_by_q.get(qid, [])

        lines.append(f"## {qid}: {text}")
        lines.append("")
        lines.append(
            f"**Status:** {status} | **Milestones:** {ms_summary} complete "
            f"| **Results:** {len(q_results)}"
        )
        lines.append("")

        if q_results:
            lines.append(
                "| Result | Milestone | Metric | Value | Confidence | Date |"
            )
            lines.append(
                "|--------|-----------|--------|-------|------------|------|"
            )
            for r in q_results:
                title = r.get("title", r.get("_filename", ""))
                fname = r.get("_filename", "")
                link = f"[{title}](../log/result/{fname}/)"
                milestone = r.get("milestone", "")
                if isinstance(milestone, list):
                    milestone = ", ".join(milestone)
                metric = r.get("metric", "")
                value = str(r.get("value", "")).replace("|", "\\|")
                confidence = r.get("confidence", "")
                date = str(r.get("date", ""))
                lines.append(
                    f"| {link} | {milestone} | {metric} | {value} "
                    f"| {confidence} | {date} |"
                )
        else:
            lines.append("No evidence recorded yet. Required milestones:")
            lines.append("")
            for mid in ms_ids:
                mdata = milestones.get(mid, {})
                mstatus = mdata.get("status", "not_started")
                check = "x" if mstatus in ("complete", "done") else " "
                lines.append(f"- [{check}] {mid}")
        lines.append("")
    return "\n".join(lines)


def _generate_index_md(
    questions: dict[str, dict],
    milestones: dict[str, dict],
    results_by_q: dict[str, list[dict]],
    q_to_m: dict[str, list[str]],
) -> str:
    """Generate index.md — plan overview landing page."""
    total_m = len(milestones)
    done_m = sum(
        1 for mdata in milestones.values()
        if mdata.get("status") in ("complete", "done")
    )
    total_q = len(questions)
    sufficient_q = sum(
        1 for qdata in questions.values()
        if qdata.get("status") in ("sufficient", "confirmed")
    )

    lines = [
        "# Research Plan",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
        f"**Progress:** {done_m}/{total_m} milestones complete "
        f"| {sufficient_q}/{total_q} questions with sufficient evidence",
        "",
        "- [Questions](questions.md) — research question registry",
        "- [Milestones](milestones.md) — progress tracker with evidence links",
        "- [Roadmap](roadmap.md) — visual dependency graph",
        "- [Evidence](evidence.md) — result index by question",
        f"- [Backlog](../log/result/) — all result notes",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# MCP tool entry point
# ---------------------------------------------------------------------------


def questio_docs_collect() -> JsonDict:
    """Generate docs/plan/ pages from plan/questions.yml and plan/milestones.yml.

    Reads the YAML plan files and result notes, then generates five markdown
    pages: questions.md, milestones.md, roadmap.md, evidence.md, index.md.
    """
    root = get_project_root()

    questions_path = root / "plan" / "questions.yml"
    milestones_path = root / "plan" / "milestones.yml"

    if not questions_path.exists():
        return json_dict({"error": f"Not found: {questions_path}"})
    if not milestones_path.exists():
        return json_dict({"error": f"Not found: {milestones_path}"})

    try:
        questions_raw = yaml.safe_load(
            questions_path.read_text(encoding="utf-8")
        )
        milestones_raw = yaml.safe_load(
            milestones_path.read_text(encoding="utf-8")
        )
    except yaml.YAMLError as exc:
        return json_dict({"error": f"YAML parse error: {exc}"})

    questions: dict[str, dict] = questions_raw.get("questions", {}) or {}
    milestones: dict[str, dict] = milestones_raw.get("milestones", {}) or {}

    # Collect result notes
    results = _collect_results(root)

    # Build cross-reference maps
    q_to_m, m_to_q = _question_milestone_map(questions)
    results_by_q = _results_by_question(results)
    results_by_m = _results_by_milestone(results)

    # Generate pages
    docs_plan = root / "docs" / "plan"
    docs_plan.mkdir(parents=True, exist_ok=True)
    generated: list[str] = []

    pages = {
        "index.md": _generate_index_md(
            questions, milestones, results_by_q, q_to_m,
        ),
        "questions.md": _generate_questions_md(
            questions, milestones, results_by_q, q_to_m,
        ),
        "milestones.md": _generate_milestones_md(
            questions, milestones, m_to_q, results_by_m,
        ),
        "roadmap.md": _generate_roadmap_md(milestones),
        "evidence.md": _generate_evidence_md(
            questions, milestones, results_by_q, q_to_m,
        ),
    }

    for filename, content in pages.items():
        out = docs_plan / filename
        out.write_text(content, encoding="utf-8")
        generated.append(str(out))

    return json_dict({
        "generated": len(generated),
        "files": generated,
        "questions": len(questions),
        "milestones": len(milestones),
        "results": len(results),
    })
