"""MCP tools: questio research orchestration — status, gap analysis, docs generation."""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

from .common import JsonDict, get_project_root, json_dict


def _parse_frontmatter(path: Path) -> dict[str, Any]:
    """Parse YAML frontmatter from a markdown file."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        return yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return {}


def _collect_results(root: Path) -> list[dict[str, Any]]:
    """Scan docs/log/result/ for result notes, return parsed frontmatter list."""
    result_dir = root / "docs" / "log" / "result"
    if not result_dir.is_dir():
        return []
    results = []
    for path in sorted(result_dir.glob("result-*.md")):
        fm = _parse_frontmatter(path)
        if fm:
            fm["_path"] = path
            fm["_filename"] = path.stem
            results.append(fm)
    return results


def _question_milestone_map(
    questions: dict[str, dict],
) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """Build question→milestones and milestone→questions mappings."""
    q_to_m: dict[str, list[str]] = {}
    m_to_q: dict[str, list[str]] = defaultdict(list)
    for qid, qdata in questions.items():
        ms = qdata.get("milestones", []) or []
        q_to_m[qid] = list(ms)
        for m in ms:
            m_to_q[m].append(qid)
    return q_to_m, dict(m_to_q)


def _results_by_question(results: list[dict[str, Any]]) -> dict[str, list[dict]]:
    """Group results by question ID."""
    by_q: dict[str, list[dict]] = defaultdict(list)
    for r in results:
        qs = r.get("question", [])
        if isinstance(qs, str):
            qs = [qs]
        for q in qs:
            by_q[q].append(r)
    return dict(by_q)


def _results_by_milestone(results: list[dict[str, Any]]) -> dict[str, list[dict]]:
    """Group results by milestone."""
    by_m: dict[str, list[dict]] = defaultdict(list)
    for r in results:
        ms = r.get("milestone", "")
        if isinstance(ms, str) and ms:
            by_m[ms].append(r)
        elif isinstance(ms, list):
            for m in ms:
                by_m[m].append(r)
    return dict(by_m)


def _milestone_status_summary(
    milestones: dict[str, dict], milestone_ids: list[str],
) -> str:
    """Return 'x/y' string for completed milestones out of total."""
    done = sum(
        1 for mid in milestone_ids
        if milestones.get(mid, {}).get("status") in ("complete", "done")
    )
    return f"{done}/{len(milestone_ids)}"


def _status_class(status: str) -> str:
    """Map status string to mermaid CSS class."""
    if status in ("complete", "done", "confirmed", "sufficient"):
        return "done"
    if status in ("in_progress", "in progress"):
        return "progress"
    return "pending"


def _sanitize_label(text: str) -> str:
    """Sanitize text for mermaid node labels."""
    return text.replace('"', "'").replace("\n", " ")


# ---------------------------------------------------------------------------
# Page generators
# ---------------------------------------------------------------------------


def _generate_questions_md(
    questions: dict[str, dict],
    milestones: dict[str, dict],
    results_by_q: dict[str, list[dict]],
    q_to_m: dict[str, list[str]],
) -> str:
    """Generate questions.md — research question registry table."""
    lines = [
        "# Research Questions",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
        "| ID | Question | Type | Status | Milestones | Evidence | Section |",
        "|----|----------|------|--------|------------|----------|---------|",
    ]
    for qid, qdata in questions.items():
        text = qdata.get("text", "")
        qtype = qdata.get("type", "")
        status = qdata.get("status", "not_started")
        ms_ids = q_to_m.get(qid, [])
        ms_summary = _milestone_status_summary(milestones, ms_ids)
        evidence_count = len(results_by_q.get(qid, []))
        section = qdata.get("manuscript_section", "")
        if section:
            section_link = f"[{section}](../manuscript/{section}/)"
        else:
            section_link = "—"
        lines.append(
            f"| {qid} | {text} | {qtype} | {status} "
            f"| {ms_summary} | {evidence_count} results | {section_link} |"
        )
    lines.append("")
    return "\n".join(lines)


def _generate_milestones_md(
    questions: dict[str, dict],
    milestones: dict[str, dict],
    m_to_q: dict[str, list[str]],
    results_by_m: dict[str, list[dict]],
) -> str:
    """Generate milestones.md — milestone tracker grouped by question."""
    lines = [
        "# Milestones",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
    ]

    # Assign milestones to groups.  A milestone belongs to a question group
    # if it serves exactly one question.  Milestones serving multiple questions
    # go into "Shared Prerequisites".
    grouped: dict[str, list[str]] = defaultdict(list)  # group label → [mid]
    shared: list[str] = []
    assigned: set[str] = set()

    for mid in milestones:
        qs = m_to_q.get(mid, [])
        if len(qs) == 1:
            grouped[qs[0]].append(mid)
            assigned.add(mid)
        elif len(qs) > 1:
            shared.append(mid)
            assigned.add(mid)

    # Milestones not referenced by any question
    orphan = [mid for mid in milestones if mid not in assigned]
    if orphan:
        shared.extend(orphan)

    def _milestone_table(milestone_ids: list[str]) -> list[str]:
        tbl = [
            "| Milestone | Status | Pipeline | Depends on | Evidence |",
            "|-----------|--------|----------|------------|----------|",
        ]
        for mid in milestone_ids:
            mdata = milestones.get(mid, {})
            desc = mdata.get("description", mid)
            status = mdata.get("status", "not_started")
            pipes = ", ".join(mdata.get("pipelines", []) or [])
            deps = ", ".join(mdata.get("depends_on", []) or []) or "—"
            evidence_list = results_by_m.get(mid, [])
            if evidence_list:
                ev_links = ", ".join(
                    f"[{r['_filename']}](../log/result/{r['_filename']}/)"
                    for r in evidence_list
                )
            else:
                ev_links = ""
            tbl.append(f"| {desc} | {status} | {pipes} | {deps} | {ev_links} |")
        return tbl

    # Shared prerequisites first
    if shared:
        lines.append("## Shared Prerequisites")
        lines.append("")
        lines.extend(_milestone_table(shared))
        lines.append("")

    # Per-question groups
    for qid, qdata in questions.items():
        q_milestones = grouped.get(qid, [])
        if not q_milestones:
            continue
        text = qdata.get("text", qid)
        lines.append(f"## {qid}: {text}")
        lines.append("")
        lines.extend(_milestone_table(q_milestones))
        lines.append("")

    return "\n".join(lines)


def _generate_roadmap_md(milestones: dict[str, dict]) -> str:
    """Generate roadmap.md — mermaid dependency graph with status coloring."""
    lines = [
        "# Roadmap",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
        "```mermaid",
        "graph LR",
    ]

    # Emit nodes
    for mid, mdata in milestones.items():
        desc = _sanitize_label(mdata.get("description", mid))
        status = mdata.get("status", "not_started")
        cls = _status_class(status)
        node_id = f"M_{mid.replace('-', '_')}"
        lines.append(f'    {node_id}["{desc}"]:::{cls}')

    lines.append("")

    # Emit edges
    for mid, mdata in milestones.items():
        deps = mdata.get("depends_on", []) or []
        target = f"M_{mid.replace('-', '_')}"
        for dep in deps:
            source = f"M_{dep.replace('-', '_')}"
            lines.append(f"    {source} --> {target}")

    lines.append("")
    lines.append("    classDef done fill:#2d6a4f,stroke:#1b4332,color:#fff")
    lines.append("    classDef progress fill:#e9c46a,stroke:#f4a261,color:#000")
    lines.append("    classDef pending fill:#adb5bd,stroke:#6c757d,color:#000")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def _generate_evidence_md(
    questions: dict[str, dict],
    milestones: dict[str, dict],
    results_by_q: dict[str, list[dict]],
    q_to_m: dict[str, list[str]],
) -> str:
    """Generate evidence.md — per-question evidence dossier."""
    lines = [
        "# Evidence",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
    ]
    for qid, qdata in questions.items():
        text = qdata.get("text", qid)
        status = qdata.get("status", "not_started")
        ms_ids = q_to_m.get(qid, [])
        ms_summary = _milestone_status_summary(milestones, ms_ids)
        q_results = results_by_q.get(qid, [])

        lines.append(f"## {qid}: {text}")
        lines.append("")
        lines.append(
            f"**Status:** {status} | **Milestones:** {ms_summary} complete "
            f"| **Results:** {len(q_results)}"
        )
        lines.append("")

        if q_results:
            lines.append(
                "| Result | Milestone | Metric | Value | Confidence | Date |"
            )
            lines.append(
                "|--------|-----------|--------|-------|------------|------|"
            )
            for r in q_results:
                title = r.get("title", r.get("_filename", ""))
                fname = r.get("_filename", "")
                link = f"[{title}](../log/result/{fname}/)"
                milestone = r.get("milestone", "")
                if isinstance(milestone, list):
                    milestone = ", ".join(milestone)
                metric = r.get("metric", "")
                value = str(r.get("value", "")).replace("|", "\\|")
                confidence = r.get("confidence", "")
                date = str(r.get("date", ""))
                lines.append(
                    f"| {link} | {milestone} | {metric} | {value} "
                    f"| {confidence} | {date} |"
                )
        else:
            lines.append("No evidence recorded yet. Required milestones:")
            lines.append("")
            for mid in ms_ids:
                mdata = milestones.get(mid, {})
                mstatus = mdata.get("status", "not_started")
                check = "x" if mstatus in ("complete", "done") else " "
                lines.append(f"- [{check}] {mid}")
        lines.append("")
    return "\n".join(lines)


def _generate_index_md(
    questions: dict[str, dict],
    milestones: dict[str, dict],
    results_by_q: dict[str, list[dict]],
    q_to_m: dict[str, list[str]],
) -> str:
    """Generate index.md — plan overview landing page."""
    total_m = len(milestones)
    done_m = sum(
        1 for mdata in milestones.values()
        if mdata.get("status") in ("complete", "done")
    )
    total_q = len(questions)
    sufficient_q = sum(
        1 for qdata in questions.values()
        if qdata.get("status") in ("sufficient", "confirmed")
    )

    lines = [
        "# Research Plan",
        "",
        "<!-- auto-generated by questio_docs_collect — do not edit -->",
        "",
        f"**Progress:** {done_m}/{total_m} milestones complete "
        f"| {sufficient_q}/{total_q} questions with sufficient evidence",
        "",
        "- [Questions](questions.md) — research question registry",
        "- [Milestones](milestones.md) — progress tracker with evidence links",
        "- [Roadmap](roadmap.md) — visual dependency graph",
        "- [Evidence](evidence.md) — result index by question",
        f"- [Backlog](../log/result/) — all result notes",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Shared data loading
# ---------------------------------------------------------------------------


def _load_plan_yaml(
    root: Path,
) -> tuple[dict[str, dict], dict[str, dict]] | str:
    """Load questions.yml and milestones.yml, return (questions, milestones).

    Returns an error string if files are missing or unparseable.
    """
    questions_path = root / "docs" / "plan" / "questions.yml"
    milestones_path = root / "docs" / "plan" / "milestones.yml"

    if not questions_path.exists():
        return f"Not found: {questions_path}"
    if not milestones_path.exists():
        return f"Not found: {milestones_path}"

    try:
        questions_raw = yaml.safe_load(
            questions_path.read_text(encoding="utf-8")
        )
        milestones_raw = yaml.safe_load(
            milestones_path.read_text(encoding="utf-8")
        )
    except yaml.YAMLError as exc:
        return f"YAML parse error: {exc}"

    questions: dict[str, dict] = (questions_raw or {}).get("questions", {}) or {}
    milestones: dict[str, dict] = (milestones_raw or {}).get("milestones", {}) or {}
    return questions, milestones


def _find_blockers(
    milestone_ids: list[str],
    milestones: dict[str, dict],
) -> list[str]:
    """Return milestone IDs from *milestone_ids* whose depends_on includes
    an incomplete milestone."""
    blocked: list[str] = []
    for mid in milestone_ids:
        mdata = milestones.get(mid, {})
        deps = mdata.get("depends_on", []) or []
        for dep in deps:
            dep_status = milestones.get(dep, {}).get("status", "not_started")
            if dep_status not in ("complete", "done"):
                blocked.append(mid)
                break
    return blocked


# ---------------------------------------------------------------------------
# MCP tools
# ---------------------------------------------------------------------------


def questio_status(question_id: str = "") -> JsonDict:
    """Overview of research state — questions, milestone progress, evidence.

    Args:
        question_id: If provided, return details for that question only.
                     Empty string returns all questions.
    """
    root = get_project_root()
    loaded = _load_plan_yaml(root)
    if isinstance(loaded, str):
        return json_dict({"error": loaded})
    questions, milestones = loaded

    # Filter to single question if requested
    if question_id:
        if question_id not in questions:
            return json_dict({"error": f"Unknown question: {question_id}"})
        questions = {question_id: questions[question_id]}

    results = _collect_results(root)
    q_to_m, _ = _question_milestone_map(questions)
    results_by_q = _results_by_question(results)

    question_summaries: list[dict[str, Any]] = []
    total_evidence = 0

    for qid, qdata in questions.items():
        ms_ids = q_to_m.get(qid, [])
        ms_progress = _milestone_status_summary(milestones, ms_ids)
        q_results = results_by_q.get(qid, [])
        evidence_count = len(q_results)
        total_evidence += evidence_count
        blockers = _find_blockers(ms_ids, milestones)

        question_summaries.append({
            "id": qid,
            "text": qdata.get("text", ""),
            "type": qdata.get("type", ""),
            "status": qdata.get("status", "not_started"),
            "milestone_progress": f"{ms_progress} complete",
            "evidence_count": evidence_count,
            "blockers": blockers,
        })

    # Overall stats (across all milestones, not just filtered)
    all_questions, all_milestones = _load_plan_yaml(root)  # type: ignore[misc]
    total_milestones = len(all_milestones)
    done_milestones = sum(
        1 for mdata in all_milestones.values()
        if mdata.get("status") in ("complete", "done")
    )

    return json_dict({
        "questions": question_summaries,
        "overall": {
            "total_questions": len(all_questions),
            "milestone_progress": f"{done_milestones}/{total_milestones} complete",
            "total_evidence": total_evidence,
        },
    })


def questio_gap(question_id: str) -> JsonDict:
    """Gap analysis for a research question — what's missing to answer it.

    Args:
        question_id: Which question to analyze (required).
    """
    root = get_project_root()
    loaded = _load_plan_yaml(root)
    if isinstance(loaded, str):
        return json_dict({"error": loaded})
    questions, milestones = loaded

    if question_id not in questions:
        return json_dict({"error": f"Unknown question: {question_id}"})

    qdata = questions[question_id]
    ms_ids = qdata.get("milestones", []) or []

    results = _collect_results(root)
    results_by_q = _results_by_question(results)
    results_by_m = _results_by_milestone(results)

    # Build milestone detail with dependency resolution
    milestone_details: list[dict[str, Any]] = []
    unmet: list[str] = []
    blocked: list[str] = []
    actionable: list[str] = []
    missing_evidence: list[str] = []

    for mid in ms_ids:
        mdata = milestones.get(mid, {})
        status = mdata.get("status", "not_started")
        deps = mdata.get("depends_on", []) or []

        # Find incomplete dependencies
        blocked_by = [
            dep for dep in deps
            if milestones.get(dep, {}).get("status", "not_started")
            not in ("complete", "done")
        ]

        # Linked evidence
        m_results = results_by_m.get(mid, [])
        evidence = [
            {
                "title": r.get("title", r.get("_filename", "")),
                "confidence": r.get("confidence", ""),
                "filename": r.get("_filename", ""),
            }
            for r in m_results
        ]

        # Highest confidence among linked results
        confidence_order = {"final": 3, "validated": 2, "preliminary": 1}
        evidence_confidence = ""
        if m_results:
            best = max(
                m_results,
                key=lambda r: confidence_order.get(
                    r.get("confidence", ""), 0
                ),
            )
            evidence_confidence = best.get("confidence", "")

        milestone_details.append({
            "id": mid,
            "description": mdata.get("description", mid),
            "status": status,
            "blocked_by": blocked_by,
            "pipelines": mdata.get("pipelines", []) or [],
            "evidence": evidence,
            "evidence_confidence": evidence_confidence,
        })

        # Classify
        if status not in ("complete", "done"):
            unmet.append(mid)
            if blocked_by:
                blocked.append(mid)
            else:
                actionable.append(mid)
        if not m_results:
            missing_evidence.append(mid)

    # Evidence from question-level linking
    q_results = results_by_q.get(question_id, [])
    q_evidence = [
        {
            "title": r.get("title", r.get("_filename", "")),
            "confidence": r.get("confidence", ""),
            "milestone": r.get("milestone", ""),
            "filename": r.get("_filename", ""),
        }
        for r in q_results
    ]

    # Generate recommendation
    recommendation = _generate_recommendation(
        question_id, qdata, milestones, unmet, blocked, actionable,
        missing_evidence,
    )

    return json_dict({
        "question": {
            "id": question_id,
            "text": qdata.get("text", ""),
            "status": qdata.get("status", "not_started"),
        },
        "milestones": milestone_details,
        "evidence": q_evidence,
        "gaps": {
            "unmet_milestones": unmet,
            "blocked_milestones": blocked,
            "actionable_milestones": actionable,
            "missing_evidence": missing_evidence,
        },
        "recommendation": recommendation,
    })


def _generate_recommendation(
    question_id: str,
    qdata: dict,
    milestones: dict[str, dict],
    unmet: list[str],
    blocked: list[str],
    actionable: list[str],
    missing_evidence: list[str],
) -> str:
    """Generate a text recommendation for highest-impact next action."""
    if not unmet:
        if missing_evidence:
            return (
                f"All milestones for {question_id} are complete but "
                f"{len(missing_evidence)} lack evidence notes. "
                f"Record results for: {', '.join(missing_evidence)}."
            )
        return (
            f"All milestones for {question_id} are complete with evidence. "
            f"Consider updating question status to 'sufficient'."
        )

    if actionable:
        # Pick the actionable milestone that unblocks the most others
        unblock_count: dict[str, int] = {}
        for mid in actionable:
            count = 0
            for other_mid, other_mdata in milestones.items():
                deps = other_mdata.get("depends_on", []) or []
                if mid in deps:
                    count += 1
            unblock_count[mid] = count

        best = max(actionable, key=lambda m: unblock_count.get(m, 0))
        best_desc = milestones.get(best, {}).get("description", best)
        pipes = milestones.get(best, {}).get("pipelines", []) or []
        pipe_str = f" (pipelines: {', '.join(pipes)})" if pipes else ""
        unblocks = unblock_count.get(best, 0)
        extra = f" Unblocks {unblocks} downstream milestone(s)." if unblocks else ""

        return (
            f"Highest impact: complete '{best}' — {best_desc}{pipe_str}.{extra}"
        )

    # All unmet milestones are blocked — find root actionable dependencies
    # by recursively traversing the full dependency graph.
    def _find_roots(start_ids: list[str], visited: set[str] | None = None) -> list[str]:
        """Walk the dependency graph to find incomplete milestones with no
        incomplete dependencies (i.e. actionable roots)."""
        if visited is None:
            visited = set()
        roots: list[str] = []
        for mid in start_ids:
            if mid in visited:
                continue
            visited.add(mid)
            mdata = milestones.get(mid, {})
            status = mdata.get("status", "not_started")
            if status in ("complete", "done"):
                continue
            deps = mdata.get("depends_on", []) or []
            incomplete_deps = [
                d for d in deps
                if milestones.get(d, {}).get("status", "not_started")
                not in ("complete", "done")
            ]
            if not incomplete_deps:
                roots.append(mid)
            else:
                roots.extend(_find_roots(incomplete_deps, visited))
        return roots

    root_actionable = _find_roots(blocked)

    if root_actionable:
        # Pick the one that unblocks the most
        unblock_count: dict[str, int] = {}
        for b in root_actionable:
            count = sum(
                1 for _, md in milestones.items()
                if b in (md.get("depends_on", []) or [])
            )
            unblock_count[b] = count
        best = max(root_actionable, key=lambda m: unblock_count.get(m, 0))
        best_desc = milestones.get(best, {}).get("description", best)
        pipes = milestones.get(best, {}).get("pipelines", []) or []
        pipe_str = f" (pipelines: {', '.join(pipes)})" if pipes else ""
        return (
            f"All {question_id} milestones are blocked. Root dependency: "
            f"'{best}' — {best_desc}{pipe_str}. Complete this first."
        )

    return (
        f"{len(unmet)} milestones remain for {question_id}, "
        f"all currently blocked by upstream dependencies."
    )


def questio_docs_collect() -> JsonDict:
    """Generate docs/plan/ pages from docs/plan/questions.yml and docs/plan/milestones.yml.

    Reads the YAML plan files and result notes, then generates five markdown
    pages: questions.md, milestones.md, roadmap.md, evidence.md, index.md.
    """
    root = get_project_root()
    loaded = _load_plan_yaml(root)
    if isinstance(loaded, str):
        return json_dict({"error": loaded})
    questions, milestones = loaded

    # Collect result notes
    results = _collect_results(root)

    # Build cross-reference maps
    q_to_m, m_to_q = _question_milestone_map(questions)
    results_by_q = _results_by_question(results)
    results_by_m = _results_by_milestone(results)

    # Generate pages
    docs_plan = root / "docs" / "plan"
    docs_plan.mkdir(parents=True, exist_ok=True)
    generated: list[str] = []

    pages = {
        "index.md": _generate_index_md(
            questions, milestones, results_by_q, q_to_m,
        ),
        "questions.md": _generate_questions_md(
            questions, milestones, results_by_q, q_to_m,
        ),
        "milestones.md": _generate_milestones_md(
            questions, milestones, m_to_q, results_by_m,
        ),
        "roadmap.md": _generate_roadmap_md(milestones),
        "evidence.md": _generate_evidence_md(
            questions, milestones, results_by_q, q_to_m,
        ),
    }

    for filename, content in pages.items():
        out = docs_plan / filename
        out.write_text(content, encoding="utf-8")
        generated.append(str(out))

    return json_dict({
        "generated": len(generated),
        "files": generated,
        "questions": len(questions),
        "milestones": len(milestones),
        "results": len(results),
    })
